{% set name = "numpy-sugar" %}
{% set version = "1.5.0" %}
{% set sha256 = "b8c08c135b369f0fd140bc2113e55fc5c838b26ba62c8fe93c118111f7d7018d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpy_sugar-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pytest-runner
    - numpy >=1.14.1
    - pypandoc
    - wheel
    - pip
  run:
    - python
    - numpy >=1.14.1
    - scipy >=0.19
    - dask >=0.15.2

test:
  requires:
    - pytest >=3.2.0
    - pytest-pep8 >=1.0.5
  imports:
    - numpy_sugar
  commands:
    - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"

about:
  home: https://github.com/limix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Missing NumPy functionalities'
  doc_url: https://numpy-sugar.readthedocs.io
  dev_url: https://github.com/limix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
