{% set name = "numpy-sugar" %}
{% set version = "1.5.1" %}
{% set sha256 = "8a0015c178f33ecd8749f3f03fc7316d073d477ab83b656aeb257a3103ce1fce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpy_sugar-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pytest-runner
    - numpy >=1.14.1
    - pypandoc
    - wheel
    - pip
  run:
    - python
    - numpy >=1.14.1
    - scipy >=0.19
    - dask >=0.15.2

test:
  requires:
    - pytest >=3.2.0
    - pytest-pep8 >=1.0.5
  imports:
    - numpy_sugar
  commands:
    - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"

about:
  home: https://github.com/limix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Missing NumPy functionalities
  doc_url: https://numpy-sugar.readthedocs.io
  dev_url: https://github.com/limix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
