{% set name = "numpy-sugar" %}
{% set version = "1.5.3" %}
{% set sha256 = "98da46042e2148568afabea02b3aa6f9d013c27369225a831d83b64d200625d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpy_sugar-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - dask >=2.18.0
    - numpy >=1.14.1
    - pytest>=6.1.2
    - python
    - scipy>=1.4.1

test:
  requires:
    - pytest >=6.1.2
  imports:
    - numpy_sugar
  commands:
    - python -c "import sys; import numpy_sugar; sys.exit(numpy_sugar.test())"

about:
  home: https://github.com/limix/numpy-sugar
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Missing NumPy functionalities
  doc_url: https://numpy-sugar.readthedocs.io
  dev_url: https://github.com/limix/numpy-sugar

extra:
  recipe-maintainers:
    - Horta
