travis:
  secure:
    BINSTAR_TOKEN: cL4hLAKZQn9gs5XtxAZ7vbfPwcTaYHKatlD9HpxA1KkWvZhQVfNKpZxEesiNi46cDoj4mtO5PuVNTwELZuNdlg5bYJGu1dAEtqTitTNqlrmuv4O8M0PWCeS49oj6oMZY0l8dZnqMCQLYCDI8GqaMxHPesRqvV4vjGAvM5aVgrjvd5aZEaqRdTTfQZisL3qJSJmQ52/KmZHflLbVZchx6z4RsKfT7tthTSYEuIwIlxw7jz0BX/InPed+wDuLgqsPuDTxjFhqwl3Y3OhlKyWm6EiIeTE7Ki7YrmSiWcNrcQwN5LOrr/LPLy/0k42YBOJ4H3WfWuUIZeMck5tei0Bsabu1XpeA6lB1cI2N8qM7C6IBlevkI6XidRjk37nY5OV9r+JQjQfVIP35mnF3Yqrnk1f3a6wkodScSh4UMj8uznCp+HqB/4ttVmQmqMojXzeb4dXfyn5Y1i9PRaqDp4m8+NoBJEqiL3JalZSDPRE3jpenNG/B+6ackbnINNpff4jjEq6hueEMcwYvnb2TPzc4F87dkHq0RDT/P7IQr7Of6MSU5jY5TAe4vyBd9DTiUSTG4j5ANVqOEV+EJI/KpmH8IIXg2ZPmCQXBaMydhU+wMhX2o0zBmwa8dFshTnUa4DD5ZhGwaUYOyvgPEK1FIMZZ6p0+QpzyS6yB5uLz8LACYEM0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
