travis:
  secure:
    BINSTAR_TOKEN: DiEnLfd+neGZN8mdGraiOqbKqyMw0gJdwug6S9BQSqwEhOsQys49F93Vrf3PwnWe/v1fvz1Q5flHykS27NI4Z/73cu5uBnTTsOCHToPZG2OZJwXaDy88OLJblRbzJQDsTPLZ5Diblhcw5eHVm0L2dlD/PFsNlFixDFsdJEc/S7s1H7HXx6msk4unpV2z051H/c1U2/fO8axX97bUvKil4TWK5/qouZ6ZRI9cgWxR+X6v26EmvEQTehdJcQ0Tu8FXOg05krxEDwpvm44NrGmRddR2OTSNcr+Jy8TqoenTEqPUTiIuOjlZrHB+75TjdfoWd6wT2Q+U8rMup5Zty8LzAW5kwGXvpavhEDz38P8AMcBBiSJYf1mrmu/8d6YHJDza/nR+WrnqEXUIUnhmRy7p8ckWcC5uUPmNMfJYQRI/uIo5v00cT2kz1/uxsjL6ety+Z/MJQqYWEkxm/tguv/1wwpBgBJhnHcCZMWR/se7zVIHUZibpuVNBSvKN08AwoTM55YsFMAeHc/a03ZNxmieT5PoHznjWzhMcA+nv8GpD9kaZElrHm+KdDmHtytQVeNTq+4kJBuCc6GdJGSN+PIQZ1XZFCyz8fOi1vNSKOySFWbrcZBO10+x6WB0jJj6xCyPMcVhEW6DQ+4oS65q5r0Wht/N+xjXSTtbxTmqNjlfEYe8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
